# This is an example file to help you get started.
# This also lets you run `zola serve` just in the themes directory
# for easier development.

# The URL the site will be built for
base_url = "http://localhost:1111"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

generate_categories_pages = true
generate_tags_pages = true

[extra]
feather_disqus_code = "<div id='disqus_thread'><div style='background: lightgrey; text-align: center; color: grey; padding: 100px 24px;'>Comments mockup</div></div>"
feather_analytics = "<script></script>"
