name = "feather"
description = "A modern blog theme"
license = "MIT"
homepage = "https://github.com/piedoom/feather"
min_version = "0.11.0"
demo = "http://vaporsoft.net/"

[extra]
feather_header_image = "/theme_images/default.gif"
feather_disqus_code = ""
feather_analytics = ""

[author]
name = "doomy"
homepage = "https://doomy.org"
