name = "feather"
description = "A fuzzy blog theme"
license = "MIT"
homepage = "https://github.com/piedoom/feather"
min_version = "0.11.0"
demo = "https://vaporsoft.net/"

[extra]
feather_disqus_domain = ""
feather_analytics = ""

[author]
name = "doomy"
homepage = "https://doomy.org"
