name = "feather"
description = "A fuzzy blog theme"
license = "MIT"
homepage = "https://github.com/piedoom/feather"
min_version = "0.19.0"
demo = "http://feather.doomy.org/"

[extra]

[extra.feather]
# theme = "light"
# hide_nav_image = false
# opengraph = { image = "" }
# disqus_id = ""
# cusdis_id = ""
# social =  { url = "https://mastodon.social/@doomy", display = "@doomy@mastodon.social" }
timezone = "America/New_York"

# [extra.feather.analytics]
# goatcounter_id = "doomy-org"

[author]
name = "doomy"
homepage = "https://doomy.org"
